app_name: "Sagar-Practice"
app_env: "development"

http_url: "0.0.0.0"
http_port: "8080"
http_allowed_origins: "*"

log_level: "Debug"

db_host: "postgres"
db_port: "5432"
db_database: "scratchdb"
db_username: "postgres"
db_password: "sagar2175"

jwt_secret_key: "this_is_a_super_secret_key_for_jwt_token_123456"
jwt_token_duration: "1h"